# Generated by Django 4.2.3 on 2023-09-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=250)),
                ('annEmploi', models.CharField(max_length=250)),
                ('ID_Annee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univers.annee')),
                ('ID_Classe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univers.classe')),
                ('ID_Modul', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univers.modul')),
            ],
        ),
    ]
